app:
  version: "@project.version@"
vep:
  mode: database
  database:
    port: 3306
    host:
    username:
    password:
  cache: 
    fasta-filename:
  forks: 4
  hgvs-max-threads: 75
  polyphen-sift-filename:
  alpha-missense-filename: