app:
  version: "@project.version@"
vep:
  mode: ${MODE}
  database:
    port: ${MYSQL_PORT}
    host: ${MYSQL_HOST}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  cache: 
    fasta-filename: ${FASTA_FILENAME}
  forks: 4
  hgvs-max-threads: 75
  polyphen-sift-filename:
  alpha-missense-filename: